package(default_visibility = ["//visibility:public"])

load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "speech_data_pb",
    srcs = [
        "speech_data.proto"
    ],
)
