package(default_visibility = ["//visibility:public"])

py_library(
     name = "operation",
     srcs = [
         "operation.py",
         "operation_params.py"
     ],
     imports = [
        "..",
     ],
)
