package(default_visibility = ["//visibility:public"])

py_library(
     name = "operation",
     srcs = [
         "operation.py",
     ],
     imports = [
        "..",
     ],
     deps = [
         ":speech_data_pb2",
     ],
)
