package(default_visibility = ["//visibility:public"])

py_binary(
    name = "ex00",
    srcs = [
        "ex00.py",
    ],
    deps = [
        "//external:soundfile",
        #"//external:librosa",
    ],
#    deps = [
#        ":tfrecord_converter",
#        ":utterance_data_pb2",
#        ":wave_util",
#    ],
    legacy_create_init = False,
)
